#!/bin/bash
# -*- mode: sh -*-

# https://julialang-s3.julialang.org/bin/linux/x64/1.11/julia-1.11.1-linux-x86_64.tar.gz
# https://julialang-s3.julialang.org/bin/linux/aarch64/1.11/julia-1.11.1-linux-aarch64.tar.gz
# https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.6-linux-x86_64.tar.gz
# https://julialang-s3.julialang.org/bin/linux/aarch64/1.10/julia-1.10.6-linux-aarch64.tar.gz

VERSION=${1-1.11.1}
VER_DIR=$(echo $VERSION | sed -e 's/\.[0-9]*$//g')

TMPDIR=${TMPDIR-/tmp}
PKG=julia-${VERSION}-linux-x86_64.tar.gz
URL=https://julialang-s3.julialang.org/bin/linux/x64/${VER_DIR}/julia-${VERSION}-linux-x86_64.tar.gz
DEST=$PROG_DIR

curl -L $URL -o ${TMPDIR}/${PKG}
cd $DEST
tar zxvf ${TMPDIR}/${PKG}

rm ${TMPDIR}/${PKG}
