#!/bin/bash
# -*- mode: sh -*-

cat <<EOF
Please ensure these dependencies are installed:
Debian/Ubuntu:
    apt-get install make build-essential \\
    libssl-dev zlib1g-dev libbz2-dev \\
    libreadline-dev libsqlite3-dev \\
    wget curl llvm libncurses5-dev xz-utils \\
    tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \\
    systemtap-sdt-dev

macOS:
    brew install openssl readline sqlite3 xz zlib
EOF

export PYTHON_CONFIGURE_OPTS="--enable-shared --with-dtrace"
pyenv install ${1-3.8.3}
