#!/bin/bash
# -*- mode: sh -*-

### Either of these
#pip install rope
pip install jedi

### flake8 for code checks
pip install flake8

### importmagic for automatic imports
pip install importmagic

### and autopep8 for automatic PEP8 formatting
pip install autopep8

### and yapf for code formatting
pip install yapf
