#!/bin/bash
#-*- mode: sh -*-

#  LuaJIT:
echo ${LUAJIT_HOME:=$HOME/programs/luajit/v2.1}
LUAJIT_LIB=$LUAJIT_HOME/lib
LUAJIT_INC=$LUAJIT_HOME/include/luajit-2.1

# Lua:
# LUA_HOME=...
# LUA_LIB=$LUA_HOME/lib
# LUA_INC=$LUA_HOME/include

echo ${NGX_SRC:=$HOME/Work/opensrc/nginx} &>/dev/null
echo ${NGX_DEST:=$HOME/programs/nginx} &>/dev/null

cd $NGX_SRC

$NGX_SRC/auto/configure --prefix=$NGX_DEST \
                        --with-debug \
                        --with-http_ssl_module \
                        --with-http_spdy_module \
                        --with-http_realip_module \
                        --with-http_addition_module \
                        --with-http_realip_module \
                        --with-http_auth_request_module \
                        --add-module=$NGX_SRC/../ngx_modules/ngx_devel_kit \
                        --add-module=$NGX_SRC/../ngx_modules/lua-nginx-module \
                        --add-module=$NGX_SRC/../ngx_modules/ngx_postgres


# config:
# worker_processes  1;
# master_process  off;
# daemon          off;
# #error_log  logs/error.log;
# #error_log  logs/error.log  debug;
# #error_log  logs/error.log  notice;
# #error_log  logs/error.log  info;
