#!/bin/bash
#-*- mode: sh -*-

MODULES_DIR=$HOME/Work/opensrc/ngx_modules
mkdir -p $MODULES_DIR/others
SAVED_WD=$PWD
SAVED_IFS="$IFS"
IFS=$'\n' MODULES=($(cat $DS3_HOME/scripts/nginx/modules-list.txt))
IFS="$SAVED_IFS"

for MOD in "${MODULES[@]}"; do
    echo "Install/Update $MOD ..."
    MOD_INFO=($MOD)
    if [[ -d $MODULES_DIR/${MOD_INFO[0]} ]]; then
        cd $MODULES_DIR/${MOD_INFO[0]}
        git pull
    else
        MOD_PATH=${MOD_INFO[0]}
        if [[ ${MOD_PATH:0:7} == "others/" ]]; then
            cd $MODULES_DIR/others
        else
            cd $MODULES_DIR
        fi
        git clone ${MOD_INFO[1]}
    fi
    cd $SAVED_WD
done
