#!/bin/bash

LUAJIT_VERSION=2.1

env_setup_ngx() {
    export LUAJIT_HOME=$HOME/programs/luajit/v$1
    export LUAJIT_LIB=$LUAJIT_HOME/lib
    export LUAJIT_INC=$LUAJIT_HOME/include/luajit-$1
    export LD_LIBRARY_PATH=$LUAJIT_LIB
    export NGX_HOME=$HOME/programs/nginx
}

echo "running nginx: $NGX_HOME/sbin/nginx -p $(pwd) $@"
env_setup_ngx $LUAJIT_VERSION
$NGX_HOME/sbin/nginx -p $(pwd) "$@"
