#!/bin/bash
#-*- mode: sh -*-

DIR=$DS3_HOME/scripts/debian
RELEASE_CODE=$(lsb_release -cs)
OUTPUT=$DIR/debian-pkg-list.$RELEASE_CODE.txt

declare -A EXCLUDED_PKGS

for PKG in $(cat debian-pkg-excluded.txt); do
    EXCLUDED_PKGS[$PKG]=1
done

#/usr/bin/aptitude -F "%p" search \!~M~i~T |sed -e "s/[[:blank:]]\+$//g"
echo > $OUTPUT

for MPKG in $(apt-mark showmanual); do
    [[ "${EXCLUDED_PKGS[$MPKG]}" != 1 ]] && echo $MPKG >> $OUTPUT
done
