#!/usr/bin/env perl

use v5.20;
use warnings;
use strict;

my $ARCH=$ARGV[0] // "x64"; # x86/x64
my $MSVC_INSTALL_PATH = "/d/programs/VisualStudio/2017/Professional";

my @MSVC_PATH = (
    "${MSVC_INSTALL_PATH}/VC/Tools/MSVC/14.10.25017/bin/Host${ARCH}/${ARCH}",
    "${MSVC_INSTALL_PATH}/Common7/IDE/VC/VCPackages",
    "${MSVC_INSTALL_PATH}/Common7/IDE/CommonExtensions/Microsoft/TestWindow",
    "${MSVC_INSTALL_PATH}/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer",
    "${MSVC_INSTALL_PATH}/MSBuild/15.0/bin/Roslyn",
    "${MSVC_INSTALL_PATH}/Team Tools/Performance Tools",
    "/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools",
    "/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 Tools",
    "/c/Program Files (x86)/Windows Kits/10/bin/${ARCH}",
    "/c/Program Files (x86)/Windows Kits/10/bin/10.0.15063.0/${ARCH}",
    "${MSVC_INSTALL_PATH}/MSBuild/15.0/bin",
    "/c/Windows/Microsoft.NET/Framework64/v4.0.30319",
    "${MSVC_INSTALL_PATH}/Common7/IDE",
    "${MSVC_INSTALL_PATH}/Common7/Tools",
);


my @INCLUDE = (
    "${MSVC_INSTALL_PATH}/VC/Tools/MSVC/14.10.25017/ATLMFC/include",
    "${MSVC_INSTALL_PATH}/VC/Tools/MSVC/14.10.25017/include",
    "/c/Program Files (x86)/Windows Kits/NETFXSDK/4.6.1/include/um",
    "/c/Program Files (x86)/Windows Kits/10/include/10.0.15063.0/ucrt",
    "/c/Program Files (x86)/Windows Kits/10/include/10.0.15063.0/shared",
    "/c/Program Files (x86)/Windows Kits/10/include/10.0.15063.0/um",
    "/c/Program Files (x86)/Windows Kits/10/include/10.0.15063.0/winrt",
);

my @LIB = (
    "${MSVC_INSTALL_PATH}/VC/Tools/MSVC/14.10.25017/ATLMFC/lib/${ARCH}",
    "${MSVC_INSTALL_PATH}/VC/Tools/MSVC/14.10.25017/lib/${ARCH}",
    "/c/Program Files (x86)/Windows Kits/NETFXSDK/4.6.1/lib/um/${ARCH}",
    "/c/Program Files (x86)/Windows Kits/10/lib/10.0.15063.0/ucrt/${ARCH}",
    "/c/Program Files (x86)/Windows Kits/10/lib/10.0.15063.0/um/${ARCH}",
);

my @LIBPATH = (
    "${MSVC_INSTALL_PATH}/VC/Tools/MSVC/14.10.25017/ATLMFC/lib/${ARCH}",
    "${MSVC_INSTALL_PATH}/VC/Tools/MSVC/14.10.25017/lib/${ARCH}",
    "/c/Program Files (x86)/Windows Kits/10/UnionMetadata/10.0.15063.0",
    "/c/Program Files (x86)/Windows Kits/10/References/10.0.15063.0",
    "/c/Windows/Microsoft.NET/Framework/v4.0.30319",
);

$ENV{PS1}= "(MSVC)" . $ENV{PS1};
$ENV{MSVC_XPATH} = (join ":", @MSVC_PATH) . $ENV{PATH};
$ENV{INCLUDE} = join ":", @INCLUDE;
$ENV{LIB} = join ":", @LIB;
$ENV{LIBPATH} = join ":", @LIBPATH;


my $RC_FILE = __FILE__ =~ s#[^/]+$#msvc-bash-rc.sh#r;

{
    exec "bash", "--rcfile", $RC_FILE;
}

print STDERR "couldn't enter MSVC-BASH: $!\n";
