#!/usr/bin/env perl

use v5.10;
use warnings;
use strict;

my @MSVC_PATH=(
    "/d/programs/VisualStudio/2017/Professional/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64",
    "/d/programs/VisualStudio/2017/Professional/Common7/IDE/VC/VCPackages",
    "/d/programs/VisualStudio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/TestWindow",
    "/d/programs/VisualStudio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer",
    "/d/programs/VisualStudio/2017/Professional/MSBuild/15.0/bin/Roslyn",
    "/d/programs/VisualStudio/2017/Professional/Team Tools/Performance Tools",
    "/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools",
    "/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 Tools",
    "/c/Program Files (x86)/Windows Kits/10/bin/x64",
    "/c/Program Files (x86)/Windows Kits/10/bin/10.0.15063.0/x64",
    "/d/programs/VisualStudio/2017/Professional/MSBuild/15.0/bin",
    "/c/Windows/Microsoft.NET/Framework64/v4.0.30319",
    "/d/programs/VisualStudio/2017/Professional/Common7/IDE",
    "/d/programs/VisualStudio/2017/Professional/Common7/Tools",
);


$ENV{PS1}= "(MSVC)" . $ENV{PS1};
$ENV{MSVC_XPATH}= (join ":", @MSVC_PATH) . $ENV{PATH};

my $RC_FILE = __FILE__ =~ s#[^/]+$#msvc-bash-rc.sh#r;

{    
    exec "bash", "--rcfile", $RC_FILE;
}

print STDERR "couldn't enter MSVC-BASH: $!\n";
