#!/usr/bin/env perl

use v5.10;
use warnings;
use strict;
use IO::Multiplex;
use Getopt::Long;
use Data::Dumper;

my ($stdin_dest, $stdout_dest, $help);

GetOptions(
    'send-stdin-to|i=s' => \$stdin_dest,
    'get-stdout-from|o=s' => \$stdout_dest,
    'help|h' => \$help
);

if ($help) {
    say <<EOF;
Usage: $0 -i file-send-stdin-to -o file-get-stdout-from
EOF
    exit;
}

open(my $inf, ">", $stdin_dest) or die("Can not open output file");
open(my $outf, "<", $stdout_dest) or die("Can not open input file");

my $mux = new IO::Multiplex;
$mux->add(\*STDIN);
$mux->add(\*STDOUT);
$mux->add($inf);
$mux->add($outf);

$mux->set_callback_object(__PACKAGE__);
$mux->loop();

sub mux_input {
    my $package = shift;
    my $mux     = shift;
    my $fh      = shift;
    my $input   = shift;

    if ($fh == $outf) {
        print STDOUT $$input;
    } elsif($fh == \*STDIN ) {
        print $inf $$input;
    }
    # Remove the input from the input buffer.
    $$input = '';
}

sub mux_close {
    print STDERR "Connection Closed\n";
    exit;
}
