#!/bin/bash
# -*- mode: sh -*-

# I failed to find a book (mostly PDF files) reader that can store my
# books on the cloud, and can synchronize my reading progression of
# each book. So I need to find my own way to synchronize my books
# between devices. This script is initally for the purpose, but now I
# upload my books onto Dropbox and my Discord server, so this script
# is rarely used.

rsync -avr ${1-$HOME/Documents/Books/} kdr2@kdr2.com:private/Books/
