#!/bin/bash

# Do NOT build one, save your time, use rustup to install a stable/beta one

: ${cargo_config?'use rustup!'}

LOCAL_RUST=$HOME/programs/rust
PREFIX=$HOME/programs/cargo

if [ -e $PREFIX/bin/cargo ]; then
    WITH_LOCAL_CARGO="--local-cargo=$PREFIX/bin/cargo"
fi

./configure \
    --local-rust-root=$LOCAL_RUST \
    --prefix=$PREFIX $WITH_LOCAL_CARGO
