#!/bin/bash

curl -sSf https://sh.rustup.rs -o /tmp/rustup.sh
chmod +x /tmp/rustup.sh

# /tmp/rustup.sh --no-modify-path --profile complete # [minimal|default|complete]
/tmp/rustup.sh --no-modify-path
