#!/bin/bash

TMPDIR=${TMPDIR-/tmp}

curl -sSf https://sh.rustup.rs -o $TMPDIR/rustup.sh
chmod +x $TMPDIR/rustup.sh

$TMPDIR/rustup.sh --no-modify-path --profile complete # [minimal|default|complete]
# $TMPDIR/rustup.sh --no-modify-path

rm $TMPDIR/rustup.sh
