#!/bin/bash
# -*- mode: sh -*-

mkdir -p $DS3_HOME/local/bin
curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o $DS3_HOME/local/bin/lein
chmod +x $DS3_HOME/local/bin/lein
lein -v
