#!/bin/bash
# -*- mode: sh -*-

mkdir -p $DS3_HOME/local/bin

TMPDIR=${TMPDIR-/tmp}

curl -L https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh -o $TMPDIR/linux-install.sh
chmod +x $TMPDIR/linux-install.sh

# With sudo, clj will be installed to /usr/local/, we can change this behavior by the option -p.
# sudo ./linux-install.sh

$TMPDIR/linux-install.sh -p $DS3_HOME/local
