#!/bin/bash

mkdir -p $DS3_HOME/local/bin
mkdir -p $DS3_HOME/local/data

curl -L https://piccolo.link/sbt-1.3.4.zip \
     -o $DS3_HOME/local/data/sbt.zip

cd $DS3_HOME/local/data/
unzip sbt.zip

ln -sf $DS3_HOME/local/data/sbt/bin/sbt $DS3_HOME/local/bin/
$DS3_HOME/local/bin/sbt console < /dev/null
$DS3_HOME/local/bin/sbt console < /dev/null
