#!/bin/bash
# -*- mode: sh -*-

VERSION=${1-1.14.4}
OS=linux
ARCH=amd64

TARBALL_NAME=go$VERSION.$OS-$ARCH.tar.gz
TARBALL_URL=https://dl.google.com/go/$TARBALL_NAME
curl $TARBALL_URL -o /tmp/$TARBALL_NAME
rm -fr $HOME/programs/go
tar -C $HOME/programs -xzf /tmp/$TARBALL_NAME
mv $HOME/programs/go $HOME/programs/go-$VERSION
