#!/bin/sh

clj -M --main cljs.main \
    --repl-opts '{:launch-browser false :port 8091 :host "100.64.0.32"}' \
    --compile-opts '{:closure-defines {clojure.browser.repl.HOST "100.64.0.32" clojure.browser.repl.PORT 8091}}' \
    --compile cljs01.core --repl
